### ISSUE TITLE
Totally Off Topic

### ISSUE THREAD

**Issue by Far117** [mlyean/agda-extras#1]
Hi Lim,

I'm sorry if this is an improper forum, but I'd like to poke your brain if I could. I noticed that you had the fastest time on [this question](https://open.kattis.com/problems/jobexpenses[https://open.kattis.com/problems/jobexpenses) in Haskell on Kattis. I've tried several things, but haven't been able to crack the 0.04 seconds mark. I even went overboard and tried to parallelize it, but that actually made it 0.01s slower.

Would you be willing to share some ideas? It's such a simple problem, and yet I'm curious about its micro-optimization.

**Comment by mlyean** [comment]
Hint: Haskell strings are slow. It is a pointless optimization.
